/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Admin
 */
public class GioiThieu extends javax.swing.JPanel {

    /**
     * Creates new form TrangChu
     */
    public GioiThieu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("        Thư viện trường học được xem là kho tàng dữ liệu đồ sộ. Ở đây có đủ mọi thể loại sách từ chuyên ngành đến phim ảnh, khoa học, lịch sử đến truyện tranh giải trí.\n        Ngoài ra, thư viện còn có những quyển sách bản quyền mà bạn khó có thể  sở hữu được nó. Hãy tận dụng thư viện trường học làm nguồn tri thức để bổ sung kiến thức cho bản thân. Ở thư viện mọi kiến thức đều đưa chia sẻ miễn phí, hãy tận dụng nó thật hiệu quả!\n       Ứng dụng  thư viện có nhiệm vụ đáp ứng nhu cầu thông tin phục vụ công tác học tập, giảng dạy và nghiên cứu khoa học cho cán bộ, giảng viên, sinh viên  trong và ngoài  trường.\n          +) Hộp tìm kiếm  sẽ là một công cụ tuyệt vời để độc giả tìm kiếm tài liệu học tập, giảng dạy và nghiên cứu nếu bạn muốn.\n          +)Độc giả có thể tự đăng ký tài khoản cá nhân của mình để tham gia sử dụng ứng dụng thư viện.\n          +) Độc giả có thể tự tạo phiếu mượn, gia hạn thêm thời gian mượn và thay đổi thông tin tài khoản cá nhân nếu muốn.\n       Ứng dụng thư viện trường học hy vọng sẽ làm hài lòng quý bạn đọc!");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
