/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Admin
 */
public class NoiQuy extends javax.swing.JPanel {

    /**
     * Creates new form TraCuuTaiLieu
     */
    public NoiQuy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("           Độc giả muốn sử dụng hệ thống thì phải có tài khoản để đăng nhập, nếu không có thì độc giả có thể tự đăng ký tài khoản cho riêng mình.\n           Độc giả(sinh viên) sẽ dùng mã sinh viên của mình để làm tên đăng nhập.\n           Mỗi lần mượn tài liệu, độc giả chỉ được mượn không quá 3 tài liệu, thời gian mượn trong vòng 14 ngày. Nếu vượt quá thời gian trên, độc giả sẽ phải chịu phạt 10.000đ/1 ngày trả trễ hẹn.\n           Nếu vì một lý do nào đó đến ngày trả tài liệu lại cho thư viện mà độc giả chưa thể trả lại thì có thể thực hiện gia hạn thêm thời gian nhưng chỉ được 1 lần duy nhất, tương ứng với 7 ngày.\n            Nếu làm hư hỏng tài liệu, thì tuỳ theo mức độ hư hại và giá tài liệu mà thư viện sẽ đưa ra mức phạt tiền phù hợp với độc giả.\n            Nếu làm mất tài liệu đã mượn, độc giả sẽ phải có trách nhiệm mua mới lại hoặc đền bù số tiền bằng với giá của tài liệu.\n            Nếu vi phạm các quy định của thư viện, độc giả có thể bị khoá tài khoản, khi đó sẽ không thể đăng nhập được vào hệ thống.\n           Độc giả chỉ có thể mượn tiếp tài liệu từ thư viện khi đã trả hết tài liệu từ lần mượn trước đó\n");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
