/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.DATACONTROLLER;
import Controller.DataControllerImp;
import Exception.InvalidDobException;
import Exception.InvalidEmailException;
import Exception.InvalidNameException;
import Exception.InvalidPhoneNumberException;
import Exception.InvalidusernameException;
import Model.DocGia;
import Model.ChiTietPhieuMuon;
import Model.PhieuMuon;
import Model.TaiLieu;
import controller.ClientCtr;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class TrangChuDocGia extends javax.swing.JFrame implements ActionListener {

    private DefaultTableModel tableModeltailieu;
    private DefaultTableModel tableModeltailieumuon;
    private DefaultTableModel tableModelthongtinpm;
    private List<TaiLieu> taiLieus;
    private List<String> danhsachdm;
    private List<String> danhsachnxb;
    private List<TaiLieu> tailieumuons;
    private PhieuMuon phieuMuon;
    private List<PhieuMuon> phieuMuons;
    private List<DocGia> docGias;
    private List<ChiTietPhieuMuon> chiTietPhieuMuons;
    private int madocgia;
    private DocGia docGia1;
    private ClientCtr clientCtr;
    private DATACONTROLLER dataControllerImp;

    /**
     * Creates new form TrangChuDocGia
     */
    public TrangChuDocGia() {
        initComponents();
        setLocationRelativeTo(null);
        dataControllerImp = new DataControllerImp();
        clientCtr = new ClientCtr();
        addbuttongroup();
        addactionlistener();
        chiTietPhieuMuons = new ArrayList<>();
        tailieumuons = new ArrayList<>();
        danhsachdm = new ArrayList<>();
        danhsachnxb = new ArrayList<>();
        phieuMuon = new PhieuMuon();
        phieuMuons = new ArrayList<>();
        docGias = new ArrayList<>();
        tableModeltailieu = (DefaultTableModel) tblsach.getModel();
        tableModeltailieumuon = (DefaultTableModel) tblsachduocmuon.getModel();
        tableModelthongtinpm = (DefaultTableModel) tblsachmuonthongtinpm.getModel();
        loadData();
        showData();
        txtmaphieu.setText(PhieuMuon.getsId() + "");
        docGia1 = new DocGia();
        URL url = this.getClass().getResource("dmtl.png");
        Image img = Toolkit.getDefaultToolkit().createImage(url);
        this.setIconImage(img);
    }

    public TrangChuDocGia(int madocgia) {
        this();
        this.madocgia = madocgia;
        for (PhieuMuon s : phieuMuons) {
            if (s.getMaBanDoc() == madocgia && !(s.getTrangThai().trim().equals("Đã trả"))) {
                showdata(s);
                break;
            }
        }
        for (DocGia banDoc : docGias) {
            if (banDoc.getMaDocGia() == madocgia) {
                docGia1 = banDoc;
                showdata1(banDoc);
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGrouptimkiemsach = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btndangxuat = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rbtimtheoten = new javax.swing.JRadioButton();
        txttimtheoten = new javax.swing.JTextField();
        rbtimtheodanhmuc = new javax.swing.JRadioButton();
        combodanhmuc = new javax.swing.JComboBox<>();
        btntimkiem = new javax.swing.JButton();
        btnlammoi = new javax.swing.JButton();
        rbtimsachtheoma = new javax.swing.JRadioButton();
        txttimsachtheoma = new javax.swing.JTextField();
        rbtimtheonxb = new javax.swing.JRadioButton();
        combonxb = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsach = new javax.swing.JTable();
        btnxemchitietsach = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmaphieu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txttendocgia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtmadocgia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblsachduocmuon = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lbsosachmuon = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbgioihan = new javax.swing.JLabel();
        btnxoa = new javax.swing.JButton();
        btnxacnhan = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtsongaymuon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtngaymuon = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtmadocgia1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtmatkhau = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txttendangnhap = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtngaysinh = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtmadocgia2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtmatkhau1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txttendangnhap1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txthoten1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtdiachi1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtngaysinh1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtemail1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtsdt1 = new javax.swing.JTextField();
        btncapnhatthongtindocgia = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lbmadocgia = new javax.swing.JLabel();
        lbtendocgia = new javax.swing.JLabel();
        lbmaphieu = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lbngaymuon = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        lbtrangthaiphieu = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lbsosachdamuon = new javax.swing.JLabel();
        lbsongaymuon = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblsachmuonthongtinpm = new javax.swing.JTable();
        btngiahan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRANG CHỦ ĐỘC GIẢ");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" THƯ VIỆN TRƯỜNG HỌC");

        btndangxuat.setBackground(new java.awt.Color(0, 102, 102));
        btndangxuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndangxuat.setForeground(new java.awt.Color(255, 255, 255));
        btndangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log out.png"))); // NOI18N
        btndangxuat.setText("Đăng xuất");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1056, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndangxuat)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndangxuat)
                .addContainerGap())
        );

        jTabbedPane1.setBackground(new java.awt.Color(0, 102, 102));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jTabbedPane1.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 51));
        jPanel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        rbtimtheoten.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rbtimtheoten.setText("Tìm  theo tên");

        txttimtheoten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        rbtimtheodanhmuc.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rbtimtheodanhmuc.setText("Tìm theo danh mục");

        combodanhmuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        combodanhmuc.setSelectedIndex(-1);

        btntimkiem.setBackground(new java.awt.Color(0, 102, 102));
        btntimkiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btntimkiem.setForeground(new java.awt.Color(255, 255, 255));
        btntimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tk.png"))); // NOI18N
        btntimkiem.setText("Tìm kiếm");

        btnlammoi.setBackground(new java.awt.Color(0, 102, 102));
        btnlammoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlammoi.setForeground(new java.awt.Color(255, 255, 255));
        btnlammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lammoi.png"))); // NOI18N
        btnlammoi.setText("Làm mới ");

        rbtimsachtheoma.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rbtimsachtheoma.setText("Tìm theo mã ");

        txttimsachtheoma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        rbtimtheonxb.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rbtimtheonxb.setText("Tìm theo NXB");

        combonxb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        combonxb.setSelectedIndex(-1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtimtheoten)
                    .addComponent(rbtimsachtheoma))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttimtheoten, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttimsachtheoma, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtimtheonxb)
                    .addComponent(rbtimtheodanhmuc))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(combodanhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(combonxb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btntimkiem)
                    .addComponent(btnlammoi))
                .addGap(16, 16, 16))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttimtheoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtimtheoten)
                    .addComponent(rbtimtheodanhmuc)
                    .addComponent(combodanhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntimkiem))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combonxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtimsachtheoma)
                        .addComponent(txttimsachtheoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbtimtheonxb)
                        .addComponent(btnlammoi)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tblsach.setBackground(new java.awt.Color(255, 255, 51));
        tblsach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã tài liệu", "Tên tài liệu", "Danh mục", "Nhà xuất bản", "Số lượng "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblsach);

        btnxemchitietsach.setBackground(new java.awt.Color(0, 102, 102));
        btnxemchitietsach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnxemchitietsach.setForeground(new java.awt.Color(255, 255, 255));
        btnxemchitietsach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chitiet.png"))); // NOI18N
        btnxemchitietsach.setText("Xem chi tiết tài liệu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnxemchitietsach, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnxemchitietsach)
                .addContainerGap())
        );

        jTabbedPane1.addTab("TRA CỨU TÀI LIỆU", new javax.swing.ImageIcon(getClass().getResource("/image/tracuu.png")), jPanel2); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN PHIẾU MƯỢN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setText("Mã phiếu");

        txtmaphieu.setEditable(false);
        txtmaphieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText(" Tên độc giả");

        txttendocgia.setEditable(false);
        txttendocgia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("Mã độc giả");

        txtmadocgia.setEditable(false);
        txtmadocgia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel6.setText("Thông tin tài liệu được mượn");

        tblsachduocmuon.setBackground(new java.awt.Color(255, 255, 51));
        tblsachduocmuon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblsachduocmuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã tài liệu", "Tên tài liệu", "Danh mục", "Tác giả", "Nhà xuất bản", "Năm xuất bản"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblsachduocmuon);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel7.setText("Tổng lượt mượn");

        lbsosachmuon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("/");

        lbgioihan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbgioihan.setText("3");

        btnxoa.setBackground(new java.awt.Color(0, 102, 102));
        btnxoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnxoa.setForeground(new java.awt.Color(255, 255, 255));
        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xoa.png"))); // NOI18N
        btnxoa.setText("Xoá");

        btnxacnhan.setBackground(new java.awt.Color(0, 102, 102));
        btnxacnhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnxacnhan.setForeground(new java.awt.Color(255, 255, 255));
        btnxacnhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chon.png"))); // NOI18N
        btnxacnhan.setText("Xác nhận");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel11.setText("Chọn số ngày mượn");

        txtsongaymuon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel8.setText("Ngày mượn");

        txtngaymuon.setEditable(false);
        txtngaymuon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(53, 53, 53)
                                        .addComponent(lbsosachmuon, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbgioihan, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 657, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(txtngaymuon)
                                        .addGap(509, 509, 509))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(txtsongaymuon)
                                .addGap(509, 509, 509)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnxacnhan, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(btnxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(txtmaphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(txttendocgia, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(txtmadocgia, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(88, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttendocgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmaphieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmadocgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbsosachmuon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbgioihan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnxoa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtngaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxacnhan)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsongaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("TẠO PHIẾU MƯỢN", new javax.swing.ImageIcon(getClass().getResource("/image/taophieu.png")), jPanel3); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 51));

        jPanel6.setBackground(new java.awt.Color(255, 255, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin độc giả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel10.setText("Mã độc giả");

        txtmadocgia1.setEditable(false);
        txtmadocgia1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel12.setText("Mật khẩu");

        txtmatkhau.setEditable(false);
        txtmatkhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel13.setText("Tên đăng nhập");

        txttendangnhap.setEditable(false);
        txttendangnhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel14.setText("Họ và tên");

        txthoten.setEditable(false);
        txthoten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel15.setText("Địa chỉ");

        txtdiachi.setEditable(false);
        txtdiachi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel16.setText("Ngày sinh");

        txtngaysinh.setEditable(false);
        txtngaysinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel17.setText("Email");

        txtemail.setEditable(false);
        txtemail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel18.setText("Số điện thoại");

        txtsdt.setEditable(false);
        txtsdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmadocgia1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(txtmatkhau)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttendangnhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthoten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addComponent(txtdiachi))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmadocgia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thay đổi thông tin cá nhân", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel19.setText("Mã độc giả");

        txtmadocgia2.setEditable(false);
        txtmadocgia2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel20.setText("Mật khẩu");

        txtmatkhau1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel21.setText("Tên đăng nhập");

        txttendangnhap1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel22.setText("Họ và tên");

        txthoten1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel23.setText("Địa chỉ");

        txtdiachi1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel24.setText("Ngày sinh");

        txtngaysinh1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel25.setText("Email");

        txtemail1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel26.setText("Số điện thoại");

        txtsdt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btncapnhatthongtindocgia.setBackground(new java.awt.Color(0, 102, 102));
        btncapnhatthongtindocgia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncapnhatthongtindocgia.setForeground(new java.awt.Color(255, 255, 255));
        btncapnhatthongtindocgia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/capnhat.png"))); // NOI18N
        btncapnhatthongtindocgia.setText("Cập nhật");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtsdt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                            .addComponent(txtemail1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmadocgia2, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(txtmatkhau1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttendangnhap1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthoten1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txtngaysinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addComponent(txtdiachi1))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncapnhatthongtindocgia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmadocgia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtmatkhau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttendangnhap1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txthoten1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtdiachi1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtngaysinh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtemail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtsdt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncapnhatthongtindocgia)
                .addGap(19, 19, 19))
        );

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("CÀI ĐẶT\n", new javax.swing.ImageIcon(getClass().getResource("/image/caidat.png")), jPanel5); // NOI18N

        jPanel8.setBackground(new java.awt.Color(255, 255, 51));

        jPanel9.setBackground(new java.awt.Color(255, 255, 51));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel27.setText("Mã phiếu");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel28.setText("Tên độc giả");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel29.setText("Mã độc giả");

        lbmadocgia.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        lbtendocgia.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        lbmaphieu.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        jLabel33.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel33.setText("Ngày mượn");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel34.setText("Trạng thái");

        lbngaymuon.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        jLabel36.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel36.setText("Số ngày mượn");

        lbtrangthaiphieu.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        jLabel38.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel38.setText("Số tài liệu mượn");

        lbsosachdamuon.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        lbsongaymuon.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbtendocgia, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(lbmadocgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbmaphieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbsosachdamuon, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(lbsongaymuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbngaymuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(104, 104, 104)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtrangthaiphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbmaphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbmadocgia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbngaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbsongaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbtrangthaiphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbtendocgia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbsosachdamuon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tblsachmuonthongtinpm.setBackground(new java.awt.Color(255, 255, 51));
        tblsachmuonthongtinpm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblsachmuonthongtinpm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã tài liệu", "Tên tài liệu", "Danh mục", "Tác giả", "Nhà xuất bản", "Năm xuất bản"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblsachmuonthongtinpm);

        btngiahan.setBackground(new java.awt.Color(0, 102, 102));
        btngiahan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btngiahan.setForeground(new java.awt.Color(255, 255, 255));
        btngiahan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/giahan.png"))); // NOI18N
        btngiahan.setText("Gia hạn");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addComponent(btngiahan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(btngiahan)
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("THÔNG TIN PHIẾU ", new javax.swing.ImageIcon(getClass().getResource("/image/thongtinphieumuon.png")), jPanel8); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuDocGia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncapnhatthongtindocgia;
    private javax.swing.JButton btndangxuat;
    private javax.swing.JButton btngiahan;
    private javax.swing.JButton btnlammoi;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnxacnhan;
    private javax.swing.JButton btnxemchitietsach;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGrouptimkiemsach;
    private javax.swing.JComboBox<String> combodanhmuc;
    private javax.swing.JComboBox<String> combonxb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbgioihan;
    private javax.swing.JLabel lbmadocgia;
    private javax.swing.JLabel lbmaphieu;
    private javax.swing.JLabel lbngaymuon;
    private javax.swing.JLabel lbsongaymuon;
    private javax.swing.JLabel lbsosachdamuon;
    private javax.swing.JLabel lbsosachmuon;
    private javax.swing.JLabel lbtendocgia;
    private javax.swing.JLabel lbtrangthaiphieu;
    private javax.swing.JRadioButton rbtimsachtheoma;
    private javax.swing.JRadioButton rbtimtheodanhmuc;
    private javax.swing.JRadioButton rbtimtheonxb;
    private javax.swing.JRadioButton rbtimtheoten;
    private javax.swing.JTable tblsach;
    private javax.swing.JTable tblsachduocmuon;
    private javax.swing.JTable tblsachmuonthongtinpm;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtdiachi1;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtemail1;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txthoten1;
    private javax.swing.JTextField txtmadocgia;
    private javax.swing.JTextField txtmadocgia1;
    private javax.swing.JTextField txtmadocgia2;
    private javax.swing.JTextField txtmaphieu;
    private javax.swing.JTextField txtmatkhau;
    private javax.swing.JTextField txtmatkhau1;
    private javax.swing.JTextField txtngaymuon;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtngaysinh1;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtsdt1;
    private javax.swing.JTextField txtsongaymuon;
    private javax.swing.JTextField txttendangnhap;
    private javax.swing.JTextField txttendangnhap1;
    private javax.swing.JTextField txttendocgia;
    private javax.swing.JTextField txttimsachtheoma;
    private javax.swing.JTextField txttimtheoten;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        var obj = e.getSource();
        if (obj.equals(btndangxuat)) {
            dispose();
            new TrangChuDocGia1().setVisible(true);
        } else if (obj.equals(btnlammoi)) {
            lamMoi();
        } else if (obj.equals(btntimkiem)) {
            timSach();
        } else if (obj.equals(btnxemchitietsach)) {
            xemChiTietSach();
        } else if (obj.equals(btnxoa)) {
            xoaSachMuon();
        } else if (obj.equals(btnxacnhan)) {
            taoPhieuMuonSach();
        } else if (obj.equals(btncapnhatthongtindocgia)) {
            capnhatthongtindocgia();
        } else if (obj.equals(btngiahan)) {
            giahan();
        }
    }

    private void addactionlistener() {
        rbtimtheoten.addActionListener(this);
        rbtimtheodanhmuc.addActionListener(this);
        btndangxuat.addActionListener(this);
        btnlammoi.addActionListener(this);
        btntimkiem.addActionListener(this);
        btnxemchitietsach.addActionListener(this);
        rbtimsachtheoma.addActionListener(this);
        btnxacnhan.addActionListener(this);
        btnxoa.addActionListener(this);
        btncapnhatthongtindocgia.addActionListener(this);
        btngiahan.addActionListener(this);
        rbtimtheonxb.addActionListener(this);

    }

    private void addbuttongroup() {
        buttonGrouptimkiemsach.add(rbtimtheoten);
        buttonGrouptimkiemsach.add(rbtimtheodanhmuc);
        buttonGrouptimkiemsach.add(rbtimsachtheoma);
        buttonGrouptimkiemsach.add(rbtimtheonxb);
    }

    private void loadData() {
        clientCtr.moSocket();
        clientCtr.guiyeucau("ok");
        taiLieus = clientCtr.nhandanhsachtailieu();
        danhsachdm = clientCtr.nhandanhsachtheloai();
        phieuMuons = clientCtr.nhandanhsachphieumuon();
        docGias = clientCtr.nhandanhsachbandoc();
        danhsachnxb = clientCtr.nhandanhsachnxb();
        editmaPhieuMuon();
        clientCtr.dongketnoi();

    }

    private void editmaPhieuMuon() {
        var maxId = PhieuMuon.getsId();
        for (PhieuMuon s : phieuMuons) {
            if (s.getMaPM() > maxId) {
                maxId = s.getMaPM();
            }

        }
        PhieuMuon.setsId(maxId + 1);
    }

    private void showData() {
        showtaiLieus();
        showcombodanhmuc();
        showcombonxb();
    }

    private void showtaiLieus() {
        tableModeltailieu.setRowCount(0);
        for (TaiLieu sach : taiLieus) {
            showSach(sach);
        }
    }
//

    private void showcombodanhmuc() {
        for (String str : danhsachdm) {
            combodanhmuc.addItem(str);
        }
    }

    private void showcombonxb() {
        for (String str : danhsachnxb) {
            combonxb.addItem(str);
        }
    }
//

    private void showSach(TaiLieu s) {
//        var a = s.getMadanhmuc();
//        var b = s.getManxb();
//        clientCtr.moSocket();
//        clientCtr.guimadanhmuc(a);
//        var c = clientCtr.nhanketqua();
//        clientCtr.guimanxb(b);
//        var d = clientCtr.nhanketqua();
        var row = new Object[]{s.getMatl(), s.getTentl(),
            s.getMadanhmuc(), s.getManxb(), s.getSoLuongCon()};
        tableModeltailieu.addRow(row);
        //clientCtr.dongketnoi();
    }

    private void timSach() {
        taiLieus.clear();
        clientCtr.moSocket();
        clientCtr.guiyeucau("oke");
        taiLieus = clientCtr.nhandanhsachtailieu();
        if (rbtimtheoten.isSelected()) {
            if (txttimtheoten.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn"
                        + " tên tài liệu cần tìm kiếm");

            } else {
                var s1 = dataControllerImp.timtailieutheoten(taiLieus,
                        txttimtheoten.getText());
                if (s1.size() > 0) {
                    JOptionPane.showMessageDialog(rootPane,
                            "Tìm thấy " + s1.size() + " kết quả");
                    tableModeltailieu.setRowCount(0);
                    for (TaiLieu s : s1) {
                        showSach(s);
                    }
                } else {
                    taiLieus.clear();
                    showtaiLieus();
                    JOptionPane.showMessageDialog(rootPane,
                            "Không tìm thấy kết quả nào");
                }

            }
        } else if (rbtimsachtheoma.isSelected()) {
            if (!txttimsachtheoma.getText().isEmpty()) {

                var s2 = dataControllerImp.
                        timtailieutheoma(taiLieus, txttimsachtheoma.getText());
                if (s2.size() > 0) {
                    tableModeltailieu.setRowCount(0);
                    for (TaiLieu s : s2) {
                        showSach(s);
                    }
                    JOptionPane.showMessageDialog(rootPane,
                            "Tìm thấy " + s2.size() + " kết quả");
                } else {
                    taiLieus.clear();
                    showtaiLieus();
                    JOptionPane.showMessageDialog(rootPane,
                            "Không tìm thấy kết quả nào");
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập"
                        + " mã tài liệu cần tìm kiếm");
            }
        } else if (rbtimtheodanhmuc.isSelected()) {
            if (combodanhmuc.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn"
                        + " danh mục tài liệu cần tìm kiếm");
            } else {
                var major1 = combodanhmuc.getSelectedItem().toString();
                var s3 = dataControllerImp.timtailieutheodanhmuc1(taiLieus, major1);
                if (s3.size() > 0) {
                    taiLieus.clear();
                    taiLieus.addAll(s3);
                    showtaiLieus();
                    JOptionPane.showMessageDialog(rootPane,
                            "Tìm thấy " + s3.size() + " kết quả");
                } else {
                    taiLieus.clear();
                    showtaiLieus();
                    JOptionPane.showMessageDialog(rootPane,
                            "Không tìm thấy kết quả nào");
                }
            }
        } else if (rbtimtheonxb.isSelected()) {
            if (combonxb.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(rootPane,
                        "Vui lòng chọn một nhà xuất bản cần tìm kiếm");
            } else {
                var major1 = combonxb.getSelectedItem().toString();
                var s3 = dataControllerImp.timtailieutheonxb1(taiLieus, major1);
                if (s3.size() > 0) {
                    taiLieus.clear();
                    taiLieus.addAll(s3);
                    showtaiLieus();
                    JOptionPane.showMessageDialog(rootPane,
                            "Tìm thấy " + s3.size() + " kết quả");
                } else {
                    taiLieus.clear();
                    showtaiLieus();
                    JOptionPane.showMessageDialog(rootPane,
                            "Không tìm thấy kết quả nào");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn"
                    + " cách thức tìm kiếm");
        }
        clientCtr.dongketnoi();
    }

    private void lamMoi() {
        buttonGrouptimkiemsach.clearSelection();
        txttimtheoten.setText("");
        txttimsachtheoma.setText("");
        combodanhmuc.removeAllItems();
        combonxb.removeAllItems();
        tableModeltailieu.setRowCount(0);
        //
        taiLieus.clear();
        danhsachdm.clear();
        danhsachnxb.clear();
        //
        clientCtr.moSocket();
        clientCtr.guiyeucau("ok");
        taiLieus = clientCtr.nhandanhsachtailieu();
        danhsachdm = clientCtr.nhandanhsachtheloai();
        phieuMuons = clientCtr.nhandanhsachphieumuon();
        docGias = clientCtr.nhandanhsachbandoc();
        danhsachnxb = clientCtr.nhandanhsachnxb();
        showtaiLieus();
        showcombodanhmuc();
        showcombonxb();
        combodanhmuc.setSelectedIndex(-1);
        combonxb.setSelectedIndex(-1);
        clientCtr.dongketnoi();
    }
//

    private void xemChiTietSach() {
        var index = tblsach.getSelectedRow();
        if (index > -1) {
            var s1 = taiLieus.get(index);
            XemChiTietSach xemChiTietSach = new XemChiTietSach(this, true, s1, lbtrangthaiphieu.getText().trim());
            xemChiTietSach.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn"
                    + "  một tài liệu cần xem!");
        }
    }
//// Mượn sách
//

    void themvaodanhsachcallback(TaiLieu s) {
        if (tailieumuons.contains(s)) {
            JOptionPane.showMessageDialog(rootPane, "Bạn đã mượn một tài liệu này rồi\n "
                    + "Vui lòng chọn tài liệu khác trong thư viện!");
        }
        if (tailieumuons.size() == 3) {
            JOptionPane.showMessageDialog(rootPane, "Bạn đã mượn đủ "
                    + "  số tài liệu cho phép của thư viện!");
        }
       if(!tailieumuons.contains(s)&& tailieumuons.size() < 3){
            tailieumuons.add(s);
            showtailieumuons();
            thietlapsosachmuon();
        }

    }
//

    private void showtailieumuons() {
        tableModeltailieumuon.setRowCount(0);
        for (TaiLieu sachmuon : tailieumuons) {
            showsachmuon(sachmuon);
        }
    }

    private void showsachmuon(TaiLieu s) {
//        var a = s.getMadanhmuc();
//        var b = s.getManxb();
//        clientCtr.moSocket();
//        clientCtr.guimadanhmuc(a);
//        var c = clientCtr.nhanketqua();
//        clientCtr.guimanxb(b);
//        var d = clientCtr.nhanketqua();
        var row = new Object[]{s.getMatl(), s.getTentl(),
            s.getMadanhmuc(), s.getTacGia(), s.getManxb(), String.valueOf(s.getNamXuatBan())};
        tableModeltailieumuon.addRow(row);
        //clientCtr.dongketnoi();
    }

    private void thietlapsosachmuon() {
        var a = tableModeltailieumuon.getRowCount();
        //var c = lbgioihan.getText();
        lbsosachmuon.setText(String.valueOf(a));
        if (a > 3) {
            lbsosachmuon.setForeground(Color.red);
            JOptionPane.showMessageDialog(rootPane, "Bạn đã mượn quá "
                    + "  số tài liệu cho phép của thư viện!");
        } else {
            lbsosachmuon.setForeground(Color.BLACK);
        }
    }
//

    private void xoaSachMuon() {
        int row = tblsachduocmuon.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(TrangChuDocGia.this,
                    "Chọn một tài liệu để xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            tailieumuons.remove(row);
            //tableModeltailieumuon.removeRow(row);
            showtailieumuons();
            thietlapsosachmuon();
        }
    }

    private void taoPhieuMuonSach() {
        var maPhieu = txtmaphieu.getText();
        var hoten = txttendocgia.getText();
        var maDocGia = txtmadocgia.getText();
        var sosachmuon = lbsosachmuon.getText();
        var format = "dd/MM/yyyy ";
        var date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat(format);
        var currentTime = dateFormat.format(date);
        var ngaymuon = txtngaymuon.getText();
        var songaymuon = txtsongaymuon.getText();
        var trangthai = " Chưa trả";

        if (maPhieu.isEmpty() || hoten.isEmpty() || maDocGia.isEmpty() || sosachmuon.isEmpty()
                || songaymuon.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng kiểm tra lại các thông "
                    + "tin trước khi mượn tài liệu!");

        } else {
            if (Integer.parseInt(songaymuon) > 14) {
                JOptionPane.showMessageDialog(TrangChuDocGia.this,
                        "Vui lòng kiểm tra lại số ngày mượn",
                        "Thất bại", JOptionPane.ERROR_MESSAGE);

            }
            if (Integer.parseInt(sosachmuon) < 0 || Integer.parseInt(sosachmuon) > 3) {
                JOptionPane.showMessageDialog(TrangChuDocGia.this,
                        "Vui lòng kiểm tra lại số lượng sách đã mượn",
                        "Thất bại", JOptionPane.ERROR_MESSAGE);
            } else {
                txtngaymuon.setText(currentTime);
                var ngaymuon1 = txtngaymuon.getText();
                try {
                    PhieuMuon phieuMuon = new PhieuMuon(Integer.parseInt(maPhieu), Integer.parseInt(maDocGia), hoten, dateFormat.parse(ngaymuon1),
                            Integer.parseInt(songaymuon), Integer.parseInt(sosachmuon), trangthai, " ");
                    if (phieuMuons.contains(phieuMuon)) {
                        JOptionPane.showMessageDialog(rootPane,
                                "Phiếu mượn có mã " + maPhieu + " đã tồn tại, vui lòng thay đổi mã phiếu!");
                    } else {
                        clientCtr.moSocket();
                        clientCtr.guiPhieuMuon(phieuMuon);
                        if (clientCtr.nhanketqua().equals("taophieumuonthanhcong")) {
                            JOptionPane.showMessageDialog(rootPane,
                                    "Tạo phiếu mượn thành công!");
                            clientCtr.dongketnoi();
                            lbmaphieu.setText(maPhieu);
                            lbmadocgia.setText(maDocGia);
                            lbtendocgia.setText(hoten);
                            lbsongaymuon.setText(songaymuon);
                            lbngaymuon.setText(ngaymuon1);
                            lbsosachdamuon.setText(sosachmuon);
                            lbtrangthaiphieu.setText(trangthai);

                            showtailieumuons1();
                        }
                        var maphieumuon = Integer.parseInt(maPhieu);
                        clientCtr.moSocket();
                        for (int i = 0; i < tableModeltailieumuon.getRowCount(); i++) {
                            ChiTietPhieuMuon ctpm = new ChiTietPhieuMuon(maphieumuon, String.valueOf(tblsachduocmuon.getValueAt(i, 0)),
                                    "", "", "");
                            chiTietPhieuMuons.add(ctpm);
                        }
                        clientCtr.guiChiTietPhieuMuons(chiTietPhieuMuons);
                        clientCtr.dongketnoi();
//                        var matailieumuons = clientCtr.nhanmasach();
//                        for (int i = 0; i < taiLieus.size(); i++) {
//                            for (int j = 0; j < matailieumuons.size(); j++) {
//                                if (taiLieus.get(i).getMaSach().compareToIgnoreCase(matailieumuons.get(j)) == 0) {
//                                   
//                                    KetNoiSql.capnhatsoluongconcuasachSql(taiLieus.get(i).getMaSach(), taiLieus.get(i).getSoLuongCon() - 1);
//                                }
//
//                            }
//
//                        }  
//                        var str = "";
//                        editmaPhieuMuon();
//                        txtmaphieu.setText(PhieuMuon.getsId() + "");
//                        txttendocgia.setText(str);
//                        txtmadocgia.setText(str);
//                        lbsosachmuon.setText(str);
//                        txtngaymuon.setText(str);
//                        txtsongaymuon.setText(str);
//                        tableModeltailieumuon.setRowCount(0);

                    }

                } catch (ParseException ex) {
                }
            }

        }

    }

    private void showtailieumuons1() {
        tableModelthongtinpm.setRowCount(0);
        for (TaiLieu sachmuon : tailieumuons) {
            showsachmuon1(sachmuon);
        }
    }

    private void showsachmuon1(TaiLieu s) {
//         var a = s.getMadanhmuc();
//        var b = s.getManxb();
//        clientCtr.moSocket();
//        clientCtr.guiyeucau(a);
//        var c = clientCtr.nhanketqua();
//        clientCtr.guiyeucau(b);
//        var d = clientCtr.nhanketqua();
        var row = new Object[]{s.getMatl(), s.getTentl(),
            s.getMadanhmuc(), s.getTacGia(), s.getManxb(), String.valueOf(s.getNamXuatBan())};
        tableModelthongtinpm.addRow(row);
        // clientCtr.dongketnoi();
    }

    private void showdata(PhieuMuon s) {
        List<TaiLieu> taiLieus1 = new ArrayList<>();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy ");
        lbmaphieu.setText(String.valueOf(s.getMaPM()));
        lbtendocgia.setText(s.getTenBanDoc());
        lbmadocgia.setText(String.valueOf(s.getMaBanDoc()));
        lbngaymuon.setText(dateFormat.format(s.getNgayMuon()));
        lbsongaymuon.setText(String.valueOf(s.getSoNgayMuon()));
        lbsosachdamuon.setText(String.valueOf(s.getSoSachMuon()));
        lbtrangthaiphieu.setText(s.getTrangThai());
        clientCtr.moSocket();
        clientCtr.guiPhieuMuon(s);
        var mataiLieus = clientCtr.nhanmasach();
        for (int i = 0; i < taiLieus.size(); i++) {
            for (int j = 0; j < mataiLieus.size(); j++) {
                if (taiLieus.get(i).getMatl().equals(mataiLieus.get(j))) {
                    taiLieus1.add(taiLieus.get(i));
                }
            }

        }

        tableModelthongtinpm.setRowCount(0);
        for (TaiLieu p : taiLieus1) {
//            var a = p.getMadanhmuc();
//        var b = p.getManxb();      
//        clientCtr.guiyeucau(a);
//        var c = clientCtr.nhanketqua();
//        clientCtr.guiyeucau(b);
//        var d = clientCtr.nhanketqua();
            var row = new Object[]{p.getMatl(), p.getTentl(),
                p.getMadanhmuc(), p.getTacGia(), p.getManxb(), p.getNamXuatBan()};
            tableModelthongtinpm.addRow(row);
        }
        clientCtr.dongketnoi();
    }
//

    private void capnhatthongtindocgia() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        var ma = txtmadocgia2.getText();
        var mk = txtmatkhau1.getText();
        var tdn = txttendangnhap1.getText();
        var hoten = txthoten1.getText();
        var diachi = txtdiachi1.getText();
        var ngaysinh = txtngaysinh1.getText();
        var sdt = txtsdt1.getText();
        var email = txtemail1.getText();
        if (ma.isEmpty() || hoten.isEmpty() || ngaysinh.isEmpty() || diachi.isEmpty()
                || sdt.isEmpty() || email.isEmpty()
                || tdn.isEmpty() || mk.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Bạn vui lòng điền đầy đủ  "
                    + "thông tin vào các ô nhập liệu!");
        } else {
            try {
                docGia1.setMatkhau(mk);
                docGia1.setTenDangNhap(tdn);
                docGia1.setFullName(hoten);
                docGia1.setDob((ngaysinh));
                docGia1.setPhoneNumber(sdt);
                docGia1.setAddress(diachi);
                docGia1.setEmail(email);
                docGia1 = new DocGia(Integer.parseInt(ma), mk, tdn, diachi, sdt, hoten, email, ngaysinh, "Mở");
                clientCtr.moSocket();
                clientCtr.guiDocgia(docGia1);
                if (clientCtr.nhanketqua().equals("suadocgiathanhcong")) {
                    JOptionPane.showMessageDialog(rootPane,
                            "Cập nhật thông tin độc giả thành công!");
                }
                clientCtr.dongketnoi();

            } catch (InvalidNameException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            } catch (InvalidDobException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            } catch (InvalidPhoneNumberException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            } catch (InvalidEmailException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            } catch (InvalidusernameException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }
    }

    private void showdata1(DocGia banDoc) {
        var format = "dd/MM/yyyy ";
        SimpleDateFormat dateFormat = new SimpleDateFormat(format);
        txtmadocgia1.setText(String.valueOf(banDoc.getMaDocGia()));
        txtmadocgia2.setText(String.valueOf(banDoc.getMaDocGia()));
        txtmatkhau.setText(banDoc.getMatkhau());
        txttendangnhap.setText(banDoc.getTenDangNhap());
        txthoten.setText(banDoc.getFullName());
        txtdiachi.setText(banDoc.getAddress());
        txtngaysinh.setText(dateFormat.format(banDoc.getDob()));
        txtsdt.setText(banDoc.getPhoneNumber());
        txtemail.setText(banDoc.getEmail());
        txttendocgia.setText(banDoc.getFullName());
        txtmadocgia.setText(String.valueOf(banDoc.getMaDocGia()));
    }

    private void giahan() {
        if (lbtrangthaiphieu.getText().trim().equals("Đang gia hạn")) {
            JOptionPane.showMessageDialog(rootPane,
                    "Bạn đã gia hạn 1 lần và không thể thực hiện tiếp!");
        } else if (lbtrangthaiphieu.getText().trim().equals("Chưa trả")) {
            var a = lbmaphieu.getText();
            var b = Integer.parseInt(lbsongaymuon.getText());
            clientCtr.moSocket();
            clientCtr.guiyeucau(a);
            if (clientCtr.nhanketqua().equals("capnhatphieumuonok")) {
                JOptionPane.showMessageDialog(rootPane,
                        "Gia hạn thành công!");
                lbtrangthaiphieu.setText("Đang gia hạn");
                lbsongaymuon.setText(String.valueOf(b + 7));
            }
            clientCtr.dongketnoi();
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Bạn cần phải tạo phiếu mượn để sử dụng chức năng gia hạn!");
        }
    }

}
