/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package serverview;

import Model.NhaXuatBan;
import Model.DanhMucTaiLieu;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class SuaNhaXuatBan extends javax.swing.JDialog  implements ActionListener{
private TrangChuThuThu trangChuThuThu;
private NhaXuatBan nhaXuatBan ;
    /**
     * Creates new form SuaNhaXuatBan
     */
    public SuaNhaXuatBan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        addActionListener();
        trangChuThuThu = (TrangChuThuThu) parent;
        URL url = this.getClass().getResource("dmtl.png");
        Image img = Toolkit.getDefaultToolkit().createImage(url);
        this.setIconImage(img);
    }
 public SuaNhaXuatBan(NhaXuatBan nhaXuatBan,java.awt.Frame parent , boolean modal) {
       this(parent, modal);
        this.nhaXuatBan = nhaXuatBan;
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmanxb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttennxb = new javax.swing.JTextField();
        btncapnhat = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnhuybo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SỬA THÔNG TIN NHÀ XUẤT BẢN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN NHÀ XUẤT BẢN");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 568, 44));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã nhà xuất bản");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 99, 127, 26));

        txtmanxb.setEditable(false);
        txtmanxb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtmanxb, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 99, 390, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tên nhà xuất bản");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 168, 130, 27));

        txttennxb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txttennxb, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 168, 390, -1));

        btncapnhat.setBackground(new java.awt.Color(0, 102, 102));
        btncapnhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncapnhat.setForeground(new java.awt.Color(255, 255, 255));
        btncapnhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/capnhat.png"))); // NOI18N
        btncapnhat.setText("Cập nhật");
        getContentPane().add(btncapnhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 350, -1, -1));

        btnxoa.setBackground(new java.awt.Color(0, 102, 102));
        btnxoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnxoa.setForeground(new java.awt.Color(255, 255, 255));
        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xoa.png"))); // NOI18N
        btnxoa.setText("Xoá ");
        getContentPane().add(btnxoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 350, -1, -1));

        btnhuybo.setBackground(new java.awt.Color(0, 102, 102));
        btnhuybo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnhuybo.setForeground(new java.awt.Color(255, 255, 255));
        btnhuybo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/huybo.png"))); // NOI18N
        btnhuybo.setText("Huỷ bỏ");
        getContentPane().add(btnhuybo, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 350, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 570, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaNhaXuatBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaNhaXuatBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaNhaXuatBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaNhaXuatBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SuaNhaXuatBan dialog = new SuaNhaXuatBan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncapnhat;
    private javax.swing.JButton btnhuybo;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtmanxb;
    private javax.swing.JTextField txttennxb;
    // End of variables declaration//GEN-END:variables

    private void addActionListener() {
          btncapnhat.addActionListener(this);
        btnhuybo.addActionListener(this);
        btnxoa.addActionListener(this);
    }

    private void showData() {
          txtmanxb.setText(String.valueOf(nhaXuatBan.getMa()));
        txttennxb.setText(nhaXuatBan.getName());
    }

    private void clearInputData() {
        
        txttennxb.setText("");
    }

    private void capNhatnxb() {
         var a = txtmanxb.getText();
        var b= txttennxb.getText();
         if (a.isEmpty() || b.isEmpty() ){
         JOptionPane.showMessageDialog(rootPane, "Các ô "
                    + "nhập liệu không được để trống");
        }
          else{ nhaXuatBan.setName(b);
          trangChuThuThu.suathongtinnxb(nhaXuatBan);
           JOptionPane.showMessageDialog(rootPane,
                        "Cập nhật thông tin  thành công");
                dispose();
             
         }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
         var obj = e.getSource();
        if (obj.equals(btncapnhat)) {
            capNhatnxb();
        } else if (obj.equals(btnhuybo)) {
            this.dispose();
        } else if (obj.equals(btnxoa)) {
            clearInputData();
        }
    }
}
